
- name: Setup Dev Environment
  hosts: all
  become: true
  roles:
    - role: base
      tags: base
    - role: configuration
      tags: configuration
    - role: nvidia # only run this role if tag specified
      tags: 
        - nvidia
        - never 
  post_tasks:
    - name: Get fastfetch output
      command: fastfetch
      register: fastfetch_output
    - debug: msg="{{ fastfetch_output.stdout }}"
