- name: Install vscode extensions
  become_user: "{{ ansible_env.SUDO_USER }}"
  command: code --install-extension {{ item }}
  loop: "{{ vscode_extensions }}"
  register: install_result
  changed_when: "'already installed' not in install_result.stdout"