
- name: Setup Dev Environment
  hosts: all
  become: true
  roles:
    - role: base
      tags: base
    - role: configuration
      tags: configuration
    - role: nvidia # only run this role if tag specified
      tags: 
        - nvidia
        - never 
  post_tasks:
    - name: Get neofetch output
      command: neofetch
      register: neofetch_output
    - debug: msg="{{ neofetch_output.stdout }}"