- name: Create additional repositories
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ item.gpgkey}}"
  loop: "{{ create_repos }}"

- name: Install additional packages
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ additional_packages }}"

- name: Set RPMFusion distro name
  set_fact: 
    rpmfusion_distro_name: "{% if ansible_distribution =='Rocky'%}el{% else %}{{ ansible_distribution | lower }}{% endif %}"

- name: Install RPMFusion package repos
  package:
    name: "{{ item }}"
    state: latest
    disable_gpg_check: true
  loop: 
    - "{{ rpmfusion_packages }}"

- name: Install packages from RPMFusion
  package:
    name: "{{ item }}"
    state: latest
  loop: 
    - "{{ additional_rpmfusion_packages }}"