- name: Include distribution specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: "packages-{{ ansible_os_family }}.yml"
- include_tasks: "additional-packages-{{ ansible_os_family }}.yml"
